name = "react-lazy-ssr-workers"
main = 'src/worker/server.js'
compatibility_flags = ["streams_enable_constructors"]

[env.production]
route = 'https://react-lazy.coolcomputerclub.com/*'

[build]
command = 'esbuild src/index.js --bundle --loader:.js=jsx --outdir=public --format=esm --splitting --minify'
watch_dir = 'src'
